version: '3.7'

services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONARQUBE_JDBC_USER=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/sonarqube
      - sonarqube_extensions:/opt/sonarqube/extensions

networks:
  default:
    external:
      name: my_network

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
