version: '3.7'

services:
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.6.2"
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      SERVER_PORT: 5601
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

networks:
  default:
    external:
      name: my_local_network