version: '3.7'

services:
  keycloak:
    image: 'jboss/keycloak'
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: localhost
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
        - '8080:8080'
