version: '3.7'

services:
  keycloak:
    image: 'jboss/keycloak'
    container_name: keycloak
    restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
        - '8080:8080'

networks:
  default:
    external:
      name: my_local_network
