version: '3.7'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.2"
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      node.name: elasticsearch
      cluster.initial_master_nodes: elasticsearch
      ES_JAVA_OPTS: -Xms1g -Xmx1g

networks:
  default:
    external:
      name: my_local_network