version: '3.7'

services:
  wordpress:
    image: 'wordpress'
    container_name: wordpress
    restart: unless-stopped
    ports:
      - '8000:80'
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

networks:
  default:
    external:
      name: my_local_network

