version: '3.7'

services:
  jfrog-artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.8.4
    container_name: jfrog-artifactory
    restart: unless-stopped
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory
    ports:
      - '9009:8081'

volumes:
  artifactory-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/artifactory-data'

networks:
  default:
    external:
      name: my_local_network
