version: '3.7'

services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql_data
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'

networks:
  default:
    external:
      name: my_local_network
