version: '3.7'

services:
  dev-minio:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    container_name: minio
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin123
    ports:
      - 9001:9000
    volumes:
      - ./minio-data:/data

networks:
  default:
    external:
      name: my_network
