version: '3.7'

services:
  kafka-zookeeper:
    container_name: kafka-zookeeper
    hostname: kafka-zookeeper
    restart: unless-stopped
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zk-data:/data
  kafka-broker:
    container_name: kafka-broker
    hostname: kafka-broker
    restart: unless-stopped
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-broker
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-data:/data

networks:
  default:
    external:
      name: my_network
